# basically stolen from https://github.com/spikecodes/libreddit/blob/master/.github/workflows/rust.yml

name: CI

on:
  push:
    paths-ignore:
      - "**.md"
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Rust nightly
        run: rustup default nightly

      - name: Cache Packages
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --release

      - uses: actions/upload-artifact@v4
        name: Upload a Build Artifact
        with:
          name: matscan
          path: target/release/matscan
